### ISSUE TITLE
Keeping text up-to-date?

### ISSUE THREAD

**Issue by clayrat** [idris-hackers/software-foundations#6]
Should the text be kept in perfect sync with the original? The book keeps getting minor updates to phrasing, e.g.: 
* https://github.com/idris-hackers/software-foundations/blob/master/src/Preface.lidr#L22 - the book now says `"offshoot" chapters` instead of `"appendices"`
* https://github.com/idris-hackers/software-foundations/blob/master/src/Preface.lidr#L52 - the book removed `the idea of` part

etc..

**Comment by yurrriq** [comment]
I'd say it's probably not a huge priority, but some semblance of parity would be nice. There's been talk of doing some more elaborate, Idris-specific rewriting at some point, since Idris differs from Coq quite a bit. In that case, maintaining minor wording tweaks would become less important (or irrelevant).

**Comment by yurrriq** [comment]
Closing in favor of #37
